name: .NET Framework 4.8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore YourSolution.sln

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # Required to run dotnet test on .NET Framework projects
          dotnet-version: '7.0.x'

      - name: Build solution
        run: msbuild Skribe.sln /p:Configuration=Release

      - name: Run tests with dotnet test
        run: |
          # Run all tests in the solution targeting .NET Framework 4.8
          dotnet test Skribe.sln --configuration Release --framework net48
