name: .NET Framework 4.8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore Skribe.sln

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # Required to run dotnet test on .NET Framework projects
          dotnet-version: '7.0.x'
          cache: true

      - name: Build
        run: dotnet build --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-build
